name: CI/CD
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Create idoc config.
        run: |
          cat > idoc.yml << EOF
          site: "RegexMate"
          description: RegexMate is a beautifully designed regex app built exclusively for macOS. With a clean and intuitive interface, it empowers you to craft and test regular expressions with ease.
          keywords: regex,expression,pattern matching,developer tools,productivity
          favicon: assets/logo.png
          logo: ./assets/logo.png
          openSource: https://github.com/jaywcjlove/regex-mate
          homepage: https://wangchujiang.com/regex-mate/
          tocs: false
          element: 
            wrapper: style=max-width:720px;
          meta:
            - <meta name="author" content="Kenny Wong">
            - <meta property="og:site_name" content="<%= site %>">
            - <meta property="og:url" content="<%=homepage%><%=RESOLVE_PATH%>">
            - <meta property="og:image" content="<%=homepage%>assets/logo.png">
            - <meta property="og:type" content="website">
            - <meta property="og:title" content="<%= title %> - idoc">
            - <meta property="og:description" content="<%= description%>">
            - <meta property="twitter:image:src" content="<%=homepage%>assets/twitter.png">
            - <meta property="twitter:site" content="@jaywcjlove">
            - <meta property="twitter:creator" content="jaywcjlove">
            - <meta property="twitter:card" content="summary_large_image">
            - <meta property="twitter:title" content="<%= title %>">
            - <meta property="twitter:description" content="<%= description%>">
          menus:
            Home: index.html
            Apps: 
              url: https://wangchujiang.com/#/app
              target: __blank
            About: 
              url: https://wangchujiang.com/#/about
              target: __blank
          sideEffectFiles:
            - README.zh.md
          footer: |
            <a href="https://wangchujiang.com/#/app" target="_blank">App</a> • 
            <a href="https://wangchujiang.com/#/projects" target="_blank">Projects</a> • 
            <a href="https://wangchujiang.com/#/sponsor" target="_blank">Sponsor</a> • 
            <a href="https://wangchujiang.com/#/app" target="_blank">More Apps</a><br /><br />
            Generated by <a href="https://github.com/jaywcjlove/idoc" target="_blank">idoc</a> v{{idocVersion}}      
          EOF

      - run: npm install idoc@1 -g
      - run: idoc
      - run: cp assets/twitter.png ./dist/assets

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          commit_message: ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist